- name: Deploy Cinesense frontend to minikube
  hosts: local
  gather_facts: false
  connection: local
  collections:
    - kubernetes.core
    #    - community.kubernetes

  vars_files:
    - group_vars/frontend/secrets.yml

  roles:
    - role: frontend
    - role: logging
